name: parking_proj
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2 
  google_maps_flutter: ^2.10.0
  intl_phone_field: ^3.2.0
  url_launcher: ^6.3.1 
  intl: ^0.17.0
  firebase_database: ^11.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/